using System;
using System.Collections.Generic;

namespace Panther.Core.Models
{
    public class Album : IIdentificable, IEquatable<Album>
    {
        #region Primary key
        /// <summary>
        /// Autogenerated album id
        /// </summary>
        public long Id { get; set; }
        #endregion


        #region Foreign keys
        /// <summary>
        /// Artist id
        /// </summary>
        public long ArtistId { get; set; }
        #endregion


        #region Album properties
        /// <summary>
        /// Album name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Album image in base64 string format
        /// </summary>
        public string EncodedImage { get; set; }

        /// <summary>
        /// Album year
        /// </summary>
        public short Year { get; set; }
        #endregion


        #region Navigation properties
        /// <summary>
        /// Artist
        /// </summary>
        public Artist Artist { get; set; }

        /// <summary>
        /// Songs
        /// </summary>
        public ICollection<Song> Songs { get; set; }
        #endregion


        #region Implementations
        public bool Equals(Album other) =>
            Id == default ? Name == other.Name : Id == other.Id;
        #endregion
    }
}
