using System;
using System.Collections.Generic;

namespace Panther.Core.Models
{
    public class Playlist : IIdentificable, IEquatable<Playlist>
    {
        #region Primary key
        /// <summary>
        /// Autogenerated playlist id
        /// </summary>
        public long Id { get; set; }
        #endregion


        #region Playlist properties
        /// <summary>
        /// Playlist name
        /// </summary>
        public string Name { get; set; }
        #endregion


        #region Navigation properties
        /// <summary>
        /// Songs
        /// </summary>
        public ICollection<SongPlaylist> SongPlaylists { get; set; }
        #endregion


        #region Implementations
        public bool Equals(Playlist other) =>
            Id == default ? Name == other.Name : Id == other.Id;
        #endregion
    }
}
