name: .NET Core Release Compilation

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Restore, build and test
    runs-on: windows-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - name: Print build number
      run: echo "Build number ${env:BUILD_NUMBER}"
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      shell: pwsh
      run: .\build.ps1
    - name: Test
      run: dotnet test --no-restore --verbosity normal
